name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
      - '.github/workflows/phpstan.yml'

permissions:
  contents: read
  id-token: write
  actions: read
  checks: read
  deployments: read
  issues: read
  discussions: read
  packages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read
      
jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch the entire history for better security
          ref: ${{ github.ref }}  # Ensure the correct branch or commit is checked out

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
