name: "Update Changelog"

on:
  release:
    types: [released]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@4c5d2f3b8b8b8b8b8b8b8b8b8b8b8b8b8b8b8b8
        with:
          ref: main

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@1c0d2f3b8b8b8b8b8b8b8b8b8b8b8b8b8b8b8b8
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@5c0b2f3b8b8b8b8b8b8b8b8b8b8b8b8b8b8b8b8
        with:
          branch: main
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
